# ==============================================================================
# Omarchy Dynamic Theme Configuration for Qutebrowser
# Automatically generated by Omarchy Theme Engine
# ============================================================================== 
# Theme mode: dark
# Primary background: #090511
# Accent: #9b2ecd
# ============================================================================== 

BG = "#090511"
BG_RGB = "9,5,17"
DARK_BG = "#09031a"
DARK_BG_RGB = "9,3,26"
DARKER_BG = "#05020f"
DARKER_BG_RGB = "5,2,15"
LIGHTER_BG = "#2a1050"
LIGHTER_BG_RGB = "42,16,80"

FG = "#e4d4f0"
ACCENT = "#9b2ecd"
MUTED = "#5c4a78"
SELECTION_BG = "#2e1f47"
SELECTION_FG = "#ffffff"

RED = "#ff5c8a"
RED_RGB = "255,92,138"
GREEN = "#39ffb0"
GREEN_RGB = "57,255,176"
YELLOW = "#f4d35e"
YELLOW_RGB = "244,211,94"
BLUE = "#7c5cff"
BLUE_RGB = "124,92,255"
MAGENTA = "#c060e0"
MAGENTA_RGB = "192,96,224"
CYAN = "#7ec8e3"

MODE = "dark"

# ------------------------------------------------------------------------------
# Window & Webpage Transparency
# ------------------------------------------------------------------------------
c.window.transparent = False

# Webpage background
c.colors.webpage.bg = BG
c.colors.webpage.preferred_color_scheme = MODE
c.colors.webpage.darkmode.enabled = (MODE == "dark")

# ------------------------------------------------------------------------------
# Tab Bar Colors (opaque)
# ------------------------------------------------------------------------------
c.colors.tabs.bar.bg = DARKER_BG

c.colors.tabs.even.bg = DARK_BG
c.colors.tabs.even.fg = MUTED
c.colors.tabs.odd.bg = DARKER_BG
c.colors.tabs.odd.fg = MUTED

c.colors.tabs.selected.even.bg = BG
c.colors.tabs.selected.even.fg = ACCENT
c.colors.tabs.selected.odd.bg = BG
c.colors.tabs.selected.odd.fg = ACCENT

c.colors.tabs.pinned.even.bg = DARK_BG
c.colors.tabs.pinned.even.fg = MUTED
c.colors.tabs.pinned.odd.bg = DARKER_BG
c.colors.tabs.pinned.odd.fg = MUTED
c.colors.tabs.pinned.selected.even.bg = BG
c.colors.tabs.pinned.selected.even.fg = ACCENT
c.colors.tabs.pinned.selected.odd.bg = BG
c.colors.tabs.pinned.selected.odd.fg = ACCENT

c.colors.tabs.indicator.start = BLUE
c.colors.tabs.indicator.stop = GREEN
c.colors.tabs.indicator.error = RED
c.colors.tabs.indicator.system = "none"

# ------------------------------------------------------------------------------
# Statusbar Colors
# ------------------------------------------------------------------------------
c.colors.statusbar.normal.bg = BG
c.colors.statusbar.normal.fg = FG

c.colors.statusbar.insert.bg = GREEN
c.colors.statusbar.insert.fg = DARKER_BG

c.colors.statusbar.passthrough.bg = BLUE
c.colors.statusbar.passthrough.fg = DARKER_BG

c.colors.statusbar.command.bg = DARKER_BG
c.colors.statusbar.command.fg = FG
c.colors.statusbar.command.private.bg = DARKER_BG
c.colors.statusbar.command.private.fg = YELLOW

c.colors.statusbar.private.bg = DARKER_BG
c.colors.statusbar.private.fg = MUTED

c.colors.statusbar.caret.bg = MAGENTA
c.colors.statusbar.caret.fg = DARKER_BG
c.colors.statusbar.caret.selection.bg = SELECTION_BG
c.colors.statusbar.caret.selection.fg = SELECTION_FG

c.colors.statusbar.progress.bg = ACCENT

c.colors.statusbar.url.fg = FG
c.colors.statusbar.url.hover.fg = CYAN
c.colors.statusbar.url.success.http.fg = YELLOW
c.colors.statusbar.url.success.https.fg = GREEN
c.colors.statusbar.url.warn.fg = YELLOW
c.colors.statusbar.url.error.fg = RED

# ------------------------------------------------------------------------------
# Completion Menu (Omnibar)
# ------------------------------------------------------------------------------
c.colors.completion.category.bg = DARK_BG
c.colors.completion.category.fg = ACCENT
c.colors.completion.category.border.top = DARK_BG
c.colors.completion.category.border.bottom = DARK_BG

c.colors.completion.even.bg = BG
c.colors.completion.odd.bg = DARKER_BG
c.colors.completion.fg = FG

c.colors.completion.item.selected.bg = SELECTION_BG
c.colors.completion.item.selected.fg = SELECTION_FG
c.colors.completion.item.selected.border.top = SELECTION_BG
c.colors.completion.item.selected.border.bottom = SELECTION_BG
c.colors.completion.item.selected.match.fg = ACCENT

c.colors.completion.match.fg = ACCENT
c.colors.completion.scrollbar.bg = DARKER_BG
c.colors.completion.scrollbar.fg = MUTED

# ------------------------------------------------------------------------------
# Context Menu
# ------------------------------------------------------------------------------
c.colors.contextmenu.menu.bg = BG
c.colors.contextmenu.menu.fg = FG
c.colors.contextmenu.selected.bg = SELECTION_BG
c.colors.contextmenu.selected.fg = SELECTION_FG
c.colors.contextmenu.disabled.bg = DARK_BG
c.colors.contextmenu.disabled.fg = MUTED

# ------------------------------------------------------------------------------
# Downloads Bar
# ------------------------------------------------------------------------------
c.colors.downloads.bar.bg = DARK_BG
c.colors.downloads.start.bg = BLUE
c.colors.downloads.start.fg = DARKER_BG
c.colors.downloads.stop.bg = GREEN
c.colors.downloads.stop.fg = DARKER_BG
c.colors.downloads.error.bg = RED
c.colors.downloads.error.fg = FG

# ------------------------------------------------------------------------------
# Hints & Keyhints
# ------------------------------------------------------------------------------
c.colors.hints.bg = ACCENT
c.colors.hints.fg = DARKER_BG
c.colors.hints.match.fg = GREEN

c.colors.keyhint.bg = BG
c.colors.keyhint.fg = FG
c.colors.keyhint.suffix.fg = YELLOW

# ------------------------------------------------------------------------------
# Messages (Notification popups)
# ------------------------------------------------------------------------------
c.colors.messages.error.bg = RED
c.colors.messages.error.border = RED
c.colors.messages.error.fg = DARKER_BG

c.colors.messages.warning.bg = YELLOW
c.colors.messages.warning.border = YELLOW
c.colors.messages.warning.fg = DARKER_BG

c.colors.messages.info.bg = DARK_BG
c.colors.messages.info.border = DARK_BG
c.colors.messages.info.fg = FG

# ------------------------------------------------------------------------------
# Prompts
# ------------------------------------------------------------------------------
c.colors.prompts.bg = BG
c.colors.prompts.border = DARK_BG
c.colors.prompts.fg = FG
c.colors.prompts.selected.bg = SELECTION_BG
c.colors.prompts.selected.fg = SELECTION_FG
